import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/ui/Navbar";
import Footer from "@/ui/Footer";
import AuthContextProvider from "@/context/Context";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Chemnitz Institutions",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} box-border  w-full min-h-screen `}>
        <AuthContextProvider>
          <Navbar />

          <Toaster position="bottom-right" />
          {children}
          <Footer />
        </AuthContextProvider>
      </body>
    </html>
  );
}
