import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/ui/Navbar";
import Footer from "@/ui/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Chemnitz Institutions",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} box-border  w-full h-full `}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
